### ISSUE TITLE
`generate-with-answers` command broken

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/csa-ccm-tools#13]
The `generate-with-answers` command is now broken as reported by @kwkwan (and I was able to reproduce below).

This can already be shown using the sample answer file:

Command:
```
bundle
bundle exec csa-ccm generate-with-answers samples/ccm-answers.yaml
```

1. Notice the generated file is called `samples/ccm-.xlsx` instead of the correct `samples/ccm-answers.xlsx`. This has to be fixed.

2. Once you open the generated file:

```
open samples/ccm-.xlsx
```

Notice this message immediately shows up:
<img width="532" alt="Screen Shot 2019-07-21 at 8 18 49 PM" src="https://user-images.githubusercontent.com/11865/61604124-1b028d00-abf5-11e9-8fc4-c75753b295c8.png">

Click "Yes", then this shows:

<img width="1266" alt="Screen Shot 2019-07-21 at 8 19 04 PM" src="https://user-images.githubusercontent.com/11865/61604134-25248b80-abf5-11e9-9d61-12abbd584ddd.png">

Click "View Log" you see this:

<img width="1155" alt="Screen Shot 2019-07-21 at 8 18 39 PM" src="https://user-images.githubusercontent.com/11865/61604144-2fdf2080-abf5-11e9-9632-b6924e4c9279.png">

In the resulting Excel file, nothing is filled. "Yes", "No", etc are all empty.

@CAMOBAP795 can you please help fix this, and also write a spec that prevents this from happening again? (i.e. first do the spec to reproduce this problem, and then fix the bug).

Thanks!

**Comment by CAMOBAP** [comment]
Fixed https://github.com/metanorma/csa-ccm-tools/pull/14

Unfortunately, don't test with MS Excel yet only with Pages app

**Comment by ronaldtse** [comment]
@CAMOBAP795 this issue still exists in an identical way with Excel. Could you please help test with it? Thanks.

**Comment by CAMOBAP** [comment]
@ronaldtse I have tested with MS Excel and got repair prompt too, but can you confirm that 

> In the resulting Excel file, nothing is filled. "Yes", "No", etc are all empty.

Still exists, in my case, I see answers for 3 top questions

Investigation in progress ... checking suggestions in https://github.com/weshatheleopard/rubyXL/issues/221

**Comment by CAMOBAP** [comment]
I have done a simple test:
```ruby
workbook = RubyXL::Parser.parse('samples/csa-caiq-v3.0.1-09-01-2017.xlsx')
workbook.write('test.xlsx')
```

And `test.xlsx` file has the same corruption, I will proceed with reporting but to `weshatheleopard/rubyXL`

@ronaldtse is that ok to attach this file to a bug report, I understand that it's in public already but still could you please confirm this?

Also may I ask you to attend fixed xlsx file here (in my trial Excel I cannot save anything)

**Comment by ronaldtse** [comment]
The fixed xlsx file is the “blank-written-repaired.xlsx” file in the other issue. Yes we can post to their rep. For I believe we might work better to fix this issue in a PR for them, not sure how long it’ll take for them to fix the problem.

**Comment by CAMOBAP** [comment]
@ronaldtse awesome research, may I ask you to confirm that answers presented in repaired xlsx file if so I propose to close this one and I will proceed with https://github.com/metanorma/csa-ccm-tools/issues/18

**Comment by ronaldtse** [comment]
> may I ask you to confirm that answers presented in repaired xlsx file

@CAMOBAP795 yes, the answers are inserted correctly now after I fixed them below:
https://github.com/metanorma/csa-ccm-tools/blob/132666d18ac9dde81e4f9a93cc6abe0bcfda9e8a/lib/csa/ccm/matrix.rb#L126-L135

They also appear in the repaired excel file properly.

**Comment by ronaldtse** [comment]
Can we keep this open for now? I don't want to close this (since this is the original error) until #18 is resolved.

Once #18 is fixed this issue should go away (after confirmation, of course).

Thanks.
